### ISSUE TITLE
Version from AnkiWeb Addon page does not work

### ISSUE THREAD

**Issue by zankaku** [jcgy/batch-unsuspend#1]
Hello,

thanks for writing this addon, it does 99,9% of what I was looking for!

However, it took me a while to get it running because it was not possible to create/load a rule due to an exception.

After a while, I figured out that `ADDON_NAME` in `const.py` is set to `batch-unsuspend` while the version downloaded via Anki needs the Addon Id `1886585793`. After changing the `ADDON_NAME` locally everything runs fine and I could make my changes to randomize the unsuspended cards.

**Comment by jcgy** [comment]
Thank you for spotting and fixing this.

I think there is a deeper issue though regarding how I reference and use the meta.json. It is structurally different when developing or installing locally compared to installing from AnkiWeb. In the latter case it is pre-populated with the information from the addon page. There is a work-around by deleting the meta.json after encountering the first error, but this is not how I want it to work.

I'm happy you found it useful and have it working though. I will temporarily take down the AnkiWeb version while I work on this and can push the update.

**Comment by jcgy** [comment]
OK, I think I have managed to iron out that issue so it should work as intended when downloading and installing via AnkiWeb. Just out of curiosity what was the 0.1% extra functionality that you wanted to be able to do?

**Comment by zankaku** [comment]
Great that you found the final solution!

What I needed, was to easily unsuspend random cards out of a certain collection of cards. Your add-on already does this perfectly, except it sorts the unsuspended cards. Locally I replaced `card_ids.sort()` with `random.shuffle(card_ids)` in `batch_logic.py`. I've been thinking of adding it as a full functionality (in the UI and so on), but that would take much more time for now.

The actual use case is learning example sentences of language grammar. They come in stacks of 5-15 cards each but I don't want to learn the same grammar point with an endless repetition of similar cards. What I wanted was to space them out over a longer time. However, unsuspending them manually for hundreds of cards would be super tedious, that's where your work comes in. It saves me tons of time because it would have taken me days of research to write this add-on. So thanks a lot!

**Comment by jcgy** [comment]
You are very welcome. This is my first add-on so it has been a learning process.

Ah okay, that's interesting. I defaulted to sorting cards in `batch_logic.py` specifically because I wanted to study sequentially through some pre-made decks. If I get time I might add in a random option in the UI to allow for this directly as other people might find this useful too. It might be useful to have some rules with randomisation and some sorted.
