### ISSUE TITLE
there is issue with unsuspending new cards with parentheses in tags

### ISSUE THREAD

**Issue by DRcl0wn** [jcgy/batch-unsuspend#3]
hi i wanted to email you but there is no way to contact with you. i used batch unsuspend with some tags couple of months ago it was working well. now when i add new tags and try to unsuspend some cards from the tag it give me the message that HSV(rule name i given to my tag) has no cards left available to un-suspend, i tried couple of other tags but same error pops up. i tried the old tags which i saved couple of months ago and the addons worked it unsuspended the card. 
please help me out my exam is near and i need this addon to work
i have not updated anki since i last used this addon.
Version ⁨2.1.65 (aa9a734f)⁩
Python 3.9.15 Qt 6.4.3 PyQt 6.4.0

**Comment by jcgy** [comment]
Hi,

Sorry you are having trouble. Just to check the basics first, do the new tags you are targeting with rules definitely have suspended cards in the card browser? That message should pop up only when all cards for the selected tag are already unsuspended.

**Comment by DRcl0wn** [comment]
all the cards are suspended in the tag

**Comment by DRcl0wn** [comment]
![Uploading suspended.png…]()

**Comment by jcgy** [comment]
Can you try attaching that screenshot again, it isn't loading? If that doesn't work I can add an email to the addon page and you can share the screenshots there.

**Comment by DRcl0wn** [comment]
yes please share an email or any social media like twitter facebook etc so i can send you the screenshots.

**Comment by jcgy** [comment]
Sure, I will update the addon page, just need a few minutes.

**Comment by DRcl0wn** [comment]
thank you for this you can't imagine how bad i need this addon to work

**Comment by DRcl0wn** [comment]
thanks a lot for helping me out

**Comment by jcgy** [comment]
No problem, hope we can figure out the issue :). I added a temporary email on the addon page at the bottom of the description section, try sending your screenshots through to that address and we can take it from there.

**Comment by DRcl0wn** [comment]
okay check your email inbox
